version: '2.1'
services:

  postgres:
    image: postgres:9.6
    container_name: migrations-postgres # this will be the adminer server
    environment:
      - POSTGRES_USER=goose
      - POSTGRES_PASSWORD=goose
      - POSTGRES_DB=goose
      - PGDATA=/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goose"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.7
    container_name: migrations-adminer
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080

  goose:
    image: fpopic/goose:1.0
    build:
      context: .
    user: 1000:1000 # put your non-root user's uid:gid (run cmd `id`)
    container_name: migrations-goose
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      # e.g. postgres://{user}:{password}@{hostname}:{port}/{database-name}
      - GOOSE_DBSTRING=postgres://goose:goose@migrations-postgres:5432/goose?sslmode=disable
    volumes:
      - ./db/migrations:/app/db/migrations:rw 
